apiVersion: v1
kind: Pod
metadata:
  name: generic-gpu-pod
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 2Gi
