# Dask scheduler pod
# This is the main coordinator for the Dask cluster

apiVersion: v1
kind: Pod
metadata:
  name: dask-scheduler
  labels:
    app: dask
    component: scheduler
spec:
  containers:
  - name: dask-scheduler
    image: daskdev/dask:latest
    command: ["dask-scheduler", "--host=0.0.0.0", "--port=8786", "--dashboard-address=0.0.0.0:8787"]
    ports:
    - containerPort: 8786
    - containerPort: 8787
    resources:
      requests:
        cpu: "0.5"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
