apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
spec:
  containers:
  - name: failing-container
    image: ubuntu
    command: ["sh", "-c", "echo 'Starting pod' && sleep 5 && echo 'About to fail' && exit 1"]
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
  restartPolicy: Never
