apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: resource-container
    image: ubuntu
    command: ["sh", "-c", "echo 'Starting resource test' && while true; do echo 'Memory usage:' && free -h && sleep 10; done"]
    resources:
      limits:
        memory: 50Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 100m
