apiVersion: v1
kind: Pod
metadata:
  name: rtx3090-pod
spec:
  containers:
  - name: rtx3090-container
    image: nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04
    command: ["sleep", "3600"]  # Sleep for 1 hour instead of infinity
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090

